// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkyEzKkPK0RI12dZeaf9L4UBqyyoFPvW4',
    appId: '1:996428957723:web:9b7c6cdd416118da5190be',
    messagingSenderId: '996428957723',
    projectId: 'ndnloginsuksesdatabase',
    authDomain: 'ndnloginsuksesdatabase.firebaseapp.com',
    storageBucket: 'ndnloginsuksesdatabase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQzQCZ62C68QGXsa53zMOWaH6SbL9nnZM',
    appId: '1:996428957723:android:0c1a4eded2c179b75190be',
    messagingSenderId: '996428957723',
    projectId: 'ndnloginsuksesdatabase',
    storageBucket: 'ndnloginsuksesdatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJj0WQDGnvlYLDZGifHUDsdqPBi5Lagg',
    appId: '1:996428957723:ios:7650b60d3c7e559d5190be',
    messagingSenderId: '996428957723',
    projectId: 'ndnloginsuksesdatabase',
    storageBucket: 'ndnloginsuksesdatabase.appspot.com',
    iosClientId: '996428957723-in7ib0krokonp723ui3m4jmtosopb2oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrudTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhJj0WQDGnvlYLDZGifHUDsdqPBi5Lagg',
    appId: '1:996428957723:ios:7650b60d3c7e559d5190be',
    messagingSenderId: '996428957723',
    projectId: 'ndnloginsuksesdatabase',
    storageBucket: 'ndnloginsuksesdatabase.appspot.com',
    iosClientId: '996428957723-in7ib0krokonp723ui3m4jmtosopb2oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCrudTesting',
  );
}
